---
sources:
  npm: true

npm:
  production_only: false

ignored:
  npm:
    - '@swc/*'
    - '@next/swc-*'
    - 'bufferutil'
    - 'canvas'
    - 'fibers'
    - 'fsevents'
    - 'nodemailer'
    - 'node-sass'
    - 'sass'
    - 'ts-node'
    - 'utf-8-validate'
    - 'webpack'

allowed:
  - 0bsd
  - apache-2.0
  - bsd-3-clause
  - bsd-2-clause
  - isc
  - mit

reviewed:
  npm:
    - '@rushstack/eslint-patch'
    - '@typescript-eslint/parser'
    - '@typescript-eslint/typescript-estree'
    - abab # BSD-3-CLAUSE
    - argparse # Python-2.0
    - aria-query # Apache-2.0
    - axe-core # MPL-2.0
    - big-integer # unlicense
    - caniuse-lite # CC-BY-4.0
    - color-convert # MIT
    - doctrine # Apache-2.0
    - dompurify # MPL-2.0 or Apache-2.0
    - electron-to-chromium # ISC
    - escodegen # BSD-2-CLAUSE
    - esquery # BSD-3-CLAUSE
    - esrecurse # BSD-2-CLAUSE
    - estraverse # MIT
    - esutils # BSD-2-CLAUSE
    - fs.realpath # ISC
    - glob # MIT
    - ignore # MIT
    - json-parse-even-better-errors # MIT
    - language-subtag-registry # ODC-BY-1.0
    - lodash # MIT
    - lodash.castarray # MIT
    - lodash.clonedeep
    - lodash.isequal # MIT
    - lodash.isplainobject # MIT
    - lodash.merge # MIT
    - lodash.uniq # MIT
    - lodash.zip # MIT
    - marked # MIT
    - mousetrap # Apache-2.0 with LLVM exception
    - pretty-format # MIT
    - readable-stream # MIT
    - source-map # BSD-3-CLAUSE
    - source-map-js # BSD-3-CLAUSE
    - string-hash # CC0-1.0
    - string_decoder # MIT
    - type-fest # MIT or CC0-1.0
    - uri-js # BSD-2-CLAUSE
