name: Verify license metadata

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  licensed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: jonabc/setup-licensed@v1
        with:
          version: '3.x'
          github_token: '${{ secrets.GITHUB_TOKEN }}'
      - run: npm install
      - run: licensed cache
      - run: licensed status
